-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 20:26:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`avions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avions` (
  `id_avio` INT NOT NULL,
  `capacitat` INT NULL,
  `model` VARCHAR(45) NULL,
  PRIMARY KEY (`id_avio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seients` (
  `id_seient` INT NOT NULL,
  `avio_id` INT NULL,
  PRIMARY KEY (`id_seient`),
  INDEX `id_avio_idx` (`avio_id` ASC) VISIBLE,
  CONSTRAINT `id_avio`
    FOREIGN KEY (`avio_id`)
    REFERENCES `mydb`.`avions` (`id_avio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
