-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 20:28:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuaris` (
  `usuaris_id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenya` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuaris_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fotografies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fotografies` (
  `fotografia_id` INT NOT NULL,
  `lloc` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`fotografia_id`),
  INDEX `usuari_id_idx` (`usuari_id` ASC) VISIBLE,
  CONSTRAINT `usuari_id`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuaris` (`usuaris_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`amistats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`amistats` (
  `usuari_id1` INT NOT NULL,
  `usuari_id2` INT NOT NULL,
  `motiu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuari_id1`, `usuari_id2`),
  INDEX `usuari_id2_idx` (`usuari_id2` ASC) VISIBLE,
  CONSTRAINT `usuari_id1`
    FOREIGN KEY (`usuari_id1`)
    REFERENCES `mydb`.`usuaris` (`usuaris_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `usuari_id2`
    FOREIGN KEY (`usuari_id2`)
    REFERENCES `mydb`.`usuaris` (`usuaris_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
