-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 20:26:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`comprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comprador` (
  `comprador_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL,
  `cognom` VARCHAR(100) NULL,
  `dni` VARCHAR(12) NULL,
  PRIMARY KEY (`comprador_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock` (
  `quadre_id` INT NOT NULL,
  `preu` DECIMAL NOT NULL,
  `autor` VARCHAR(100) NULL,
  `comprador_id` INT NULL,
  PRIMARY KEY (`quadre_id`),
  INDEX `comprador_id_idx` (`comprador_id` ASC) VISIBLE,
  CONSTRAINT `comprador_id`
    FOREIGN KEY (`comprador_id`)
    REFERENCES `mydb`.`comprador` (`comprador_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
