-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 20:27:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`autors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autors` (
  `autor_id` INT NOT NULL,
  `direccio` VARCHAR(100) NOT NULL,
  `numero_llibres` INT NOT NULL,
  PRIMARY KEY (`autor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cataleg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cataleg` (
  `llibre_id` INT NOT NULL,
  `stock` INT NOT NULL,
  `preu` DECIMAL NOT NULL,
  `autor_id` INT NOT NULL,
  PRIMARY KEY (`llibre_id`),
  INDEX `autor_id_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `autor_id`
    FOREIGN KEY (`autor_id`)
    REFERENCES `mydb`.`autors` (`autor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuaris` (
  `usuari_id` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `contrasenya` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`usuari_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facturas` (
  `factura_id` INT NOT NULL,
  `usuari_id` INT NOT NULL,
  PRIMARY KEY (`factura_id`),
  INDEX `usuari_id_idx` (`usuari_id` ASC) VISIBLE,
  CONSTRAINT `usuari_id`
    FOREIGN KEY (`usuari_id`)
    REFERENCES `mydb`.`usuaris` (`usuari_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`linies_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`linies_factura` (
  `factura_id` INT NOT NULL,
  `llibre_id` INT NOT NULL,
  `quantitat` INT NOT NULL,
  PRIMARY KEY (`factura_id`),
  INDEX `llibre_id_idx` (`llibre_id` ASC) VISIBLE,
  CONSTRAINT `factura_id`
    FOREIGN KEY (`factura_id`)
    REFERENCES `mydb`.`facturas` (`factura_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `llibre_id`
    FOREIGN KEY (`llibre_id`)
    REFERENCES `mydb`.`cataleg` (`llibre_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
